import { sql } from 'drizzle-orm';
import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

// ---- Organization (school) — data-isolation unit; M1 runs a single one, but every model carries orgId ----
export const organizations = sqliteTable('organizations', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

// ---- Teacher — self-built auth (username + password); identity decoupled from credentials ----
export const teachers = sqliteTable('teachers', {
  id: text('id').primaryKey(),
  orgId: text('org_id')
    .notNull()
    .references(() => organizations.id),
  name: text('name').notNull(),
  username: text('username').notNull().unique(),
  role: text('role').notNull().default('teacher'), // owner | teacher
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

// ---- Credential — decouples login providers. password rows carry the hash;
// wechat rows point at the wechat_account bound to this teacher (self-service
// bind: enter web username+password once inside the miniapp).
export const credentials = sqliteTable('credentials', {
  id: text('id').primaryKey(),
  teacherId: text('teacher_id')
    .notNull()
    .references(() => teachers.id),
  provider: text('provider').notNull(), // password | wechat
  secret: text('secret'), // password: "salt:hash"; wechat: null
  wechatAccountId: text('wechat_account_id').references(() => wechatAccounts.id),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

// ---- WechatAccount — pure identity (teacher/parent share it; the role comes
// from what it's linked to, never from a flag on the account) ----
export const wechatAccounts = sqliteTable('wechat_accounts', {
  id: text('id').primaryKey(),
  openid: text('openid').notNull().unique(),
  unionid: text('unionid'),
  nickname: text('nickname'),
  avatarUrl: text('avatar_url'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  lastLoginAt: text('last_login_at'),
});

// ---- Class ----
export const classes = sqliteTable('classes', {
  id: text('id').primaryKey(),
  orgId: text('org_id')
    .notNull()
    .references(() => organizations.id),
  name: text('name').notNull(),
  level: text('level'), // 新概念二册 etc. (optional grade / book, free text)
  notes: text('notes'), // 班级资源 — free-form markdown kept by the teachers
  textbook: integer('textbook'), // 教材册数 1-4 (structured, for 课文复习 defaults)
  homeworkTemplate: text('homework_template'), // 作业模板 — {lesson_number}/{date}/{class_name} vars
  teacherId: text('teacher_id').references(() => teachers.id), // 负责老师
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

// ---- ClassInvite — one-shot expiring invite generated by a teacher inside the
// miniapp and shared to a group chat. Replaces the old per-class fixed code:
// multiple live invites may coexist, each dies at its own expires_at.
export const classInvites = sqliteTable('class_invites', {
  id: text('id').primaryKey(),
  classId: text('class_id')
    .notNull()
    .references(() => classes.id),
  token: text('token').notNull().unique(),
  createdBy: text('created_by').references(() => teachers.id),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  expiresAt: text('expires_at').notNull(),
});

// ---- Student ----
export const students = sqliteTable('students', {
  id: text('id').primaryKey(),
  classId: text('class_id')
    .notNull()
    .references(() => classes.id),
  name: text('name').notNull(),
  enName: text('en_name'),
  parentPhone: text('parent_phone'),
  photoUrl: text('photo_url'),
  source: text('source').notNull(), // parent | teacher
  // active 在读 | suspended 停课 | archived 已归档 — non-active students never
  // enter setup/classroom/session snapshots; archived ones also leave counts.
  status: text('status').notNull().default('active'),
  // Dormant since the wechat_account rework (kept for a future login-free H5
  // share link); miniapp access now goes through student_wechat_bindings.
  recapToken: text('recap_token').notNull().unique(),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

// ---- StudentWechatBinding — N:M: one parent account sees several kids, one
// kid is visible to both parents. Only teachers create rows (via link).
export const studentWechatBindings = sqliteTable(
  'student_wechat_bindings',
  {
    id: text('id').primaryKey(),
    studentId: text('student_id')
      .notNull()
      .references(() => students.id),
    wechatAccountId: text('wechat_account_id')
      .notNull()
      .references(() => wechatAccounts.id),
    createdBy: text('created_by').references(() => teachers.id),
    createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  },
  (t) => [uniqueIndex('uq_student_wechat').on(t.studentId, t.wechatAccountId)],
);

// ---- JoinRequest — what registering through an invite produces. No student
// row is created here: the teacher later links the request to an existing
// student (or dismisses it). One live pending request per (class, account).
export const joinRequests = sqliteTable(
  'join_requests',
  {
    id: text('id').primaryKey(),
    classId: text('class_id')
      .notNull()
      .references(() => classes.id),
    wechatAccountId: text('wechat_account_id')
      .notNull()
      .references(() => wechatAccounts.id),
    inviteId: text('invite_id').references(() => classInvites.id),
    cnName: text('cn_name').notNull(),
    enName: text('en_name'),
    parentPhone: text('parent_phone'),
    photoKey: text('photo_key'),
    status: text('status').notNull().default('pending'), // pending | linked | dismissed
    linkedStudentId: text('linked_student_id').references(() => students.id),
    handledBy: text('handled_by').references(() => teachers.id),
    handledAt: text('handled_at'),
    createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  },
  (t) => [uniqueIndex('uq_join_request_pending').on(t.classId, t.wechatAccountId).where(sql`status = 'pending'`)],
);

// ---- ClassGroup — the class's single default grouping ----
export const classGroups = sqliteTable('class_groups', {
  id: text('id').primaryKey(),
  classId: text('class_id')
    .notNull()
    .references(() => classes.id),
  name: text('name').notNull(),
  emoji: text('emoji'),
  orderIndex: integer('order_index').notNull().default(0),
});

export const classGroupMemberships = sqliteTable('class_group_memberships', {
  id: text('id').primaryKey(),
  classGroupId: text('class_group_id')
    .notNull()
    .references(() => classGroups.id),
  studentId: text('student_id')
    .notNull()
    .references(() => students.id),
});

// ---- ClassSession — one "start class" session ----
export const classSessions = sqliteTable('class_sessions', {
  id: text('id').primaryKey(),
  classId: text('class_id')
    .notNull()
    .references(() => classes.id),
  teacherId: text('teacher_id').references(() => teachers.id),
  date: text('date').notNull(), // YYYY-MM-DD
  lessonNumber: integer('lesson_number'),
  lessonTitle: text('lesson_title'),
  status: text('status').notNull().default('ended'), // ongoing | ended
  plannedDurationMin: integer('planned_duration_min').notNull().default(120),
  startedAt: text('started_at'),
  endedAt: text('ended_at'),
  // Idempotency key for the offline-first end-class commit (decision 10): the
  // client's local session id, so a retried submit returns the existing row
  // instead of double-inserting. Null for legacy/seeded sessions.
  clientSessionId: text('client_session_id').unique(),
  // 作业布置 — authored on the session detail page AFTER the commit (own PUT,
  // never part of the commit payload/compat contract).
  homeworkContent: text('homework_content'),
  reviewBook: integer('review_book'), // 课文复习: 第几册 (1-4)
  reviewLesson: integer('review_lesson'), // 课文复习: 第几课
});

// ---- SessionGroup — snapshot of the default grouping at start; adjustable mid-class ----
export const sessionGroups = sqliteTable('session_groups', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => classSessions.id),
  name: text('name').notNull(),
  emoji: text('emoji'),
  orderIndex: integer('order_index').notNull().default(0),
});

export const sessionMemberships = sqliteTable('session_memberships', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => classSessions.id),
  studentId: text('student_id')
    .notNull()
    .references(() => students.id),
  sessionGroupId: text('session_group_id').references(() => sessionGroups.id),
  attendance: text('attendance').notNull().default('present'), // present | absent
});

// ---- ScoreEvent — ledger; single source of truth for all derived scores ----
export const scoreEvents = sqliteTable('score_events', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => classSessions.id),
  targetType: text('target_type').notNull(), // group | student
  targetId: text('target_id').notNull(),
  sessionGroupId: text('session_group_id').references(() => sessionGroups.id),
  delta: integer('delta').notNull(), // +1 or -1
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  createdBy: text('created_by'),
});

// ---- CheckRecord — recitation / homework qualitative labels ----
export const checkRecords = sqliteTable('check_records', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => classSessions.id),
  studentId: text('student_id')
    .notNull()
    .references(() => students.id),
  type: text('type').notNull(), // recitation | homework
  status: text('status').notNull(),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

// ---- OrgTag — org-wide 奖章 tag library (upserted by end-class commits) ----
// Deliberate exception to "only teachers/classes carry org_id": tags are an
// org-root entity with no class to hang off, so they sit next to teachers.
export const orgTags = sqliteTable(
  'org_tags',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id),
    name: text('name').notNull(),
    createdBy: text('created_by'),
    createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  },
  (t) => [uniqueIndex('uq_org_tag_name').on(t.orgId, sql`${t.name} COLLATE NOCASE`)],
);

// ---- SessionTag — one 奖章 awarded to a student in one session ----
// tag_name is a point-in-time snapshot (precedent: session_groups.name), so a
// future library rename never rewrites history; tag_id is the aggregation hook.
export const sessionTags = sqliteTable('session_tags', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => classSessions.id),
  studentId: text('student_id')
    .notNull()
    .references(() => students.id),
  tagId: text('tag_id')
    .notNull()
    .references(() => orgTags.id),
  tagName: text('tag_name').notNull(),
  createdBy: text('created_by'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});
